In [12]:
import test_python as lib

lib.add(1,2)

Adding numbers 1 and 2

3

In [13]:
import new_dir.lib1 as lib1

lib1.func('a')

printing input: a

'foo'

In [15]:
import new_dir

dir(new_dir)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'lib1']

In [22]:
import json
with open('Repo/new_dir/newjson.json', 'r') as f:
    dict = json.load(f)

In [25]:
pd.DataFrame(dict).to_csv('test.csv')

In [26]:
df = pd.read_csv('test.csv')
df

   Unnamed: 0  key1  key2
0           0  val1  val2
1           1  val3  val4

In [27]:
from os import listdir as ls
ls()

['testfile.ipynb',
 'new_text.txt',
 'Data',
 'test.csv',
 'Repo',
 'new_text2.txt',
 'test.py']

In [ ]:
# some more changes